### ISSUE TITLE
Datatype Standards

### ISSUE THREAD

**Issue by moemyself3** [toros-astro/imageredux#15]
We have had conversations about the concepts of how the data should be processed ie ccddata vs writing to file and passing file list.

It seems that for the processing of few images CCDData is a speedy process, but processing hundreds of files may prove not to be.

We can look into database/table solutions for handling the names.

Thoughts and potential solutions?

**Comment by rcamuccio** [comment]
Just a few clarifying questions for you, @moemyself3:
Do we have any quantitative measurement about the efficiency of processing CCDData type objects versus another method?
What other data structures would work? -- (e.g. perhaps an array handles more efficiently?)

**Comment by martinberoiz** [comment]
I talked about this with @juanlg7, too, there is this sort of trade off between having all images in memory, which is faster but may potentially clog the machine ram, or the other extreme which is saving every file to disk but having a performance hit since I/O operations tend to be the bottleneck most of the time. This is a discussion we should have. 

My opinion is that we should work in memory as much as we can (with CCDData objects) and save those files to disk that are important (like master flats, darks... maybe some others). But if we're saving anything to disk, there should also be a way to let know the calling party where it was saved and under what name.

**Comment by juanlg7** [comment]
I agree with Martin on that we should just work with CCDData objects, and only keep masters and final calibrated stacks of light images.

**Comment by moemyself3** [comment]
Keep on file only: Master Flat, Master Dark, and Individual Calibrated images

Use CCDData for intermediate steps.
